# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpc_test_pb2 as grpc__test__pb2


class HelloServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.unaryCall = channel.unary_unary(
        '/com.webank.eggroll.grpc.test.HelloService/unaryCall',
        request_serializer=grpc__test__pb2.HelloRequest.SerializeToString,
        response_deserializer=grpc__test__pb2.HelloResponse.FromString,
        )
    self.push = channel.stream_unary(
        '/com.webank.eggroll.grpc.test.HelloService/push',
        request_serializer=grpc__test__pb2.HelloRequest.SerializeToString,
        response_deserializer=grpc__test__pb2.HelloResponse.FromString,
        )
    self.pull = channel.unary_unary(
        '/com.webank.eggroll.grpc.test.HelloService/pull',
        request_serializer=grpc__test__pb2.HelloRequest.SerializeToString,
        response_deserializer=grpc__test__pb2.HelloResponse.FromString,
        )


class HelloServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def unaryCall(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def push(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def pull(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'unaryCall': grpc.unary_unary_rpc_method_handler(
          servicer.unaryCall,
          request_deserializer=grpc__test__pb2.HelloRequest.FromString,
          response_serializer=grpc__test__pb2.HelloResponse.SerializeToString,
      ),
      'push': grpc.stream_unary_rpc_method_handler(
          servicer.push,
          request_deserializer=grpc__test__pb2.HelloRequest.FromString,
          response_serializer=grpc__test__pb2.HelloResponse.SerializeToString,
      ),
      'pull': grpc.unary_unary_rpc_method_handler(
          servicer.pull,
          request_deserializer=grpc__test__pb2.HelloRequest.FromString,
          response_serializer=grpc__test__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'com.webank.eggroll.grpc.test.HelloService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
