# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meta.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='meta.proto',
    package='com.webank.eggroll.core.meta',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
      '\n\nmeta.proto\x12\x1c\x63om.webank.eggroll.core.meta\"&\n\x08\x45ndpoint\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"_\n\nServerNode\x12\n\n\x02id\x18\x01 \x01(\t\x12\x38\n\x08\x65ndpoint\x18\x02 \x01(\x0b\x32&.com.webank.eggroll.core.meta.Endpoint\x12\x0b\n\x03tag\x18\x03 \x01(\t\"a\n\rServerCluster\x12\n\n\x02id\x18\x01 \x01(\t\x12\x37\n\x05nodes\x18\x02 \x03(\x0b\x32(.com.webank.eggroll.core.meta.ServerNode\x12\x0b\n\x03tag\x18\x03 \x01(\t\"%\n\x07\x46unctor\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"P\n\x0cStoreLocator\x12\x11\n\tstoreType\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\"\x86\x01\n\x05Store\x12@\n\x0cstoreLocator\x18\x01 \x01(\x0b\x32*.com.webank.eggroll.core.meta.StoreLocator\x12;\n\npartitions\x18\x02 \x03(\x0b\x32\'.com.webank.eggroll.core.meta.Partition\"\x91\x01\n\tPartition\x12\n\n\x02id\x18\x01 \x01(\t\x12@\n\x0cstoreLocator\x18\x02 \x01(\x0b\x32*.com.webank.eggroll.core.meta.StoreLocator\x12\x36\n\x04node\x18\x03 \x01(\x0b\x32(.com.webank.eggroll.core.meta.ServerNode\"\xc3\x01\n\x03Job\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x33\n\x06inputs\x18\x03 \x03(\x0b\x32#.com.webank.eggroll.core.meta.Store\x12\x34\n\x07outputs\x18\x04 \x03(\x0b\x32#.com.webank.eggroll.core.meta.Store\x12\x37\n\x08\x66unctors\x18\x05 \x03(\x0b\x32%.com.webank.eggroll.core.meta.Functor\"\xc3\x01\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x37\n\x06inputs\x18\x03 \x03(\x0b\x32\'.com.webank.eggroll.core.meta.Partition\x12\x38\n\x07outputs\x18\x04 \x03(\x0b\x32\'.com.webank.eggroll.core.meta.Partition\x12.\n\x03job\x18\x05 \x01(\x0b\x32!.com.webank.eggroll.core.meta.Jobb\x06proto3')
)

_ENDPOINT = _descriptor.Descriptor(
    name='Endpoint',
    full_name='com.webank.eggroll.core.meta.Endpoint',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
      _descriptor.FieldDescriptor(
          name='host', full_name='com.webank.eggroll.core.meta.Endpoint.host',
          index=0,
          number=1, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='port', full_name='com.webank.eggroll.core.meta.Endpoint.port',
          index=1,
          number=2, type=5, cpp_type=1, label=1,
          has_default_value=False, default_value=0,
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=44,
    serialized_end=82,
)

_SERVERNODE = _descriptor.Descriptor(
    name='ServerNode',
    full_name='com.webank.eggroll.core.meta.ServerNode',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
      _descriptor.FieldDescriptor(
          name='id', full_name='com.webank.eggroll.core.meta.ServerNode.id',
          index=0,
          number=1, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='endpoint',
          full_name='com.webank.eggroll.core.meta.ServerNode.endpoint', index=1,
          number=2, type=11, cpp_type=10, label=1,
          has_default_value=False, default_value=None,
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='tag', full_name='com.webank.eggroll.core.meta.ServerNode.tag',
          index=2,
          number=3, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=84,
    serialized_end=179,
)

_SERVERCLUSTER = _descriptor.Descriptor(
    name='ServerCluster',
    full_name='com.webank.eggroll.core.meta.ServerCluster',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
      _descriptor.FieldDescriptor(
          name='id', full_name='com.webank.eggroll.core.meta.ServerCluster.id',
          index=0,
          number=1, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='nodes',
          full_name='com.webank.eggroll.core.meta.ServerCluster.nodes', index=1,
          number=2, type=11, cpp_type=10, label=3,
          has_default_value=False, default_value=[],
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='tag',
          full_name='com.webank.eggroll.core.meta.ServerCluster.tag', index=2,
          number=3, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=181,
    serialized_end=278,
)

_FUNCTOR = _descriptor.Descriptor(
    name='Functor',
    full_name='com.webank.eggroll.core.meta.Functor',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
      _descriptor.FieldDescriptor(
          name='name', full_name='com.webank.eggroll.core.meta.Functor.name',
          index=0,
          number=1, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='body', full_name='com.webank.eggroll.core.meta.Functor.body',
          index=1,
          number=2, type=12, cpp_type=9, label=1,
          has_default_value=False, default_value=_b(""),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=280,
    serialized_end=317,
)

_STORELOCATOR = _descriptor.Descriptor(
    name='StoreLocator',
    full_name='com.webank.eggroll.core.meta.StoreLocator',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
      _descriptor.FieldDescriptor(
          name='storeType',
          full_name='com.webank.eggroll.core.meta.StoreLocator.storeType',
          index=0,
          number=1, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='namespace',
          full_name='com.webank.eggroll.core.meta.StoreLocator.namespace',
          index=1,
          number=2, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='name',
          full_name='com.webank.eggroll.core.meta.StoreLocator.name', index=2,
          number=3, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='path',
          full_name='com.webank.eggroll.core.meta.StoreLocator.path', index=3,
          number=4, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=319,
    serialized_end=399,
)

_STORE = _descriptor.Descriptor(
    name='Store',
    full_name='com.webank.eggroll.core.meta.Store',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
      _descriptor.FieldDescriptor(
          name='storeLocator',
          full_name='com.webank.eggroll.core.meta.Store.storeLocator', index=0,
          number=1, type=11, cpp_type=10, label=1,
          has_default_value=False, default_value=None,
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='partitions',
          full_name='com.webank.eggroll.core.meta.Store.partitions', index=1,
          number=2, type=11, cpp_type=10, label=3,
          has_default_value=False, default_value=[],
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=402,
    serialized_end=536,
)

_PARTITION = _descriptor.Descriptor(
    name='Partition',
    full_name='com.webank.eggroll.core.meta.Partition',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
      _descriptor.FieldDescriptor(
          name='id', full_name='com.webank.eggroll.core.meta.Partition.id',
          index=0,
          number=1, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='storeLocator',
          full_name='com.webank.eggroll.core.meta.Partition.storeLocator',
          index=1,
          number=2, type=11, cpp_type=10, label=1,
          has_default_value=False, default_value=None,
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='node', full_name='com.webank.eggroll.core.meta.Partition.node',
          index=2,
          number=3, type=11, cpp_type=10, label=1,
          has_default_value=False, default_value=None,
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=539,
    serialized_end=684,
)

_JOB = _descriptor.Descriptor(
    name='Job',
    full_name='com.webank.eggroll.core.meta.Job',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
      _descriptor.FieldDescriptor(
          name='id', full_name='com.webank.eggroll.core.meta.Job.id', index=0,
          number=1, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='name', full_name='com.webank.eggroll.core.meta.Job.name',
          index=1,
          number=2, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='inputs', full_name='com.webank.eggroll.core.meta.Job.inputs',
          index=2,
          number=3, type=11, cpp_type=10, label=3,
          has_default_value=False, default_value=[],
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='outputs', full_name='com.webank.eggroll.core.meta.Job.outputs',
          index=3,
          number=4, type=11, cpp_type=10, label=3,
          has_default_value=False, default_value=[],
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='functors',
          full_name='com.webank.eggroll.core.meta.Job.functors', index=4,
          number=5, type=11, cpp_type=10, label=3,
          has_default_value=False, default_value=[],
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=687,
    serialized_end=882,
)

_TASK = _descriptor.Descriptor(
    name='Task',
    full_name='com.webank.eggroll.core.meta.Task',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
      _descriptor.FieldDescriptor(
          name='id', full_name='com.webank.eggroll.core.meta.Task.id', index=0,
          number=1, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='name', full_name='com.webank.eggroll.core.meta.Task.name',
          index=1,
          number=2, type=9, cpp_type=9, label=1,
          has_default_value=False, default_value=_b("").decode('utf-8'),
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='inputs', full_name='com.webank.eggroll.core.meta.Task.inputs',
          index=2,
          number=3, type=11, cpp_type=10, label=3,
          has_default_value=False, default_value=[],
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='outputs', full_name='com.webank.eggroll.core.meta.Task.outputs',
          index=3,
          number=4, type=11, cpp_type=10, label=3,
          has_default_value=False, default_value=[],
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
      _descriptor.FieldDescriptor(
          name='job', full_name='com.webank.eggroll.core.meta.Task.job',
          index=4,
          number=5, type=11, cpp_type=10, label=1,
          has_default_value=False, default_value=None,
          message_type=None, enum_type=None, containing_type=None,
          is_extension=False, extension_scope=None,
          serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=885,
    serialized_end=1080,
)

_SERVERNODE.fields_by_name['endpoint'].message_type = _ENDPOINT
_SERVERCLUSTER.fields_by_name['nodes'].message_type = _SERVERNODE
_STORE.fields_by_name['storeLocator'].message_type = _STORELOCATOR
_STORE.fields_by_name['partitions'].message_type = _PARTITION
_PARTITION.fields_by_name['storeLocator'].message_type = _STORELOCATOR
_PARTITION.fields_by_name['node'].message_type = _SERVERNODE
_JOB.fields_by_name['inputs'].message_type = _STORE
_JOB.fields_by_name['outputs'].message_type = _STORE
_JOB.fields_by_name['functors'].message_type = _FUNCTOR
_TASK.fields_by_name['inputs'].message_type = _PARTITION
_TASK.fields_by_name['outputs'].message_type = _PARTITION
_TASK.fields_by_name['job'].message_type = _JOB
DESCRIPTOR.message_types_by_name['Endpoint'] = _ENDPOINT
DESCRIPTOR.message_types_by_name['ServerNode'] = _SERVERNODE
DESCRIPTOR.message_types_by_name['ServerCluster'] = _SERVERCLUSTER
DESCRIPTOR.message_types_by_name['Functor'] = _FUNCTOR
DESCRIPTOR.message_types_by_name['StoreLocator'] = _STORELOCATOR
DESCRIPTOR.message_types_by_name['Store'] = _STORE
DESCRIPTOR.message_types_by_name['Partition'] = _PARTITION
DESCRIPTOR.message_types_by_name['Job'] = _JOB
DESCRIPTOR.message_types_by_name['Task'] = _TASK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Endpoint = _reflection.GeneratedProtocolMessageType('Endpoint',
                                                    (_message.Message,), {
                                                      'DESCRIPTOR': _ENDPOINT,
                                                      '__module__': 'meta_pb2'
                                                      # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.meta.Endpoint)
                                                    })
_sym_db.RegisterMessage(Endpoint)

ServerNode = _reflection.GeneratedProtocolMessageType('ServerNode',
                                                      (_message.Message,), {
                                                        'DESCRIPTOR': _SERVERNODE,
                                                        '__module__': 'meta_pb2'
                                                        # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.meta.ServerNode)
                                                      })
_sym_db.RegisterMessage(ServerNode)

ServerCluster = _reflection.GeneratedProtocolMessageType('ServerCluster',
                                                         (_message.Message,), {
                                                           'DESCRIPTOR': _SERVERCLUSTER,
                                                           '__module__': 'meta_pb2'
                                                           # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.meta.ServerCluster)
                                                         })
_sym_db.RegisterMessage(ServerCluster)

Functor = _reflection.GeneratedProtocolMessageType('Functor',
                                                   (_message.Message,), {
                                                     'DESCRIPTOR': _FUNCTOR,
                                                     '__module__': 'meta_pb2'
                                                     # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.meta.Functor)
                                                   })
_sym_db.RegisterMessage(Functor)

StoreLocator = _reflection.GeneratedProtocolMessageType('StoreLocator',
                                                        (_message.Message,), {
                                                          'DESCRIPTOR': _STORELOCATOR,
                                                          '__module__': 'meta_pb2'
                                                          # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.meta.StoreLocator)
                                                        })
_sym_db.RegisterMessage(StoreLocator)

Store = _reflection.GeneratedProtocolMessageType('Store', (_message.Message,), {
  'DESCRIPTOR': _STORE,
  '__module__': 'meta_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.meta.Store)
})
_sym_db.RegisterMessage(Store)

Partition = _reflection.GeneratedProtocolMessageType('Partition',
                                                     (_message.Message,), {
                                                       'DESCRIPTOR': _PARTITION,
                                                       '__module__': 'meta_pb2'
                                                       # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.meta.Partition)
                                                     })
_sym_db.RegisterMessage(Partition)

Job = _reflection.GeneratedProtocolMessageType('Job', (_message.Message,), {
  'DESCRIPTOR': _JOB,
  '__module__': 'meta_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.meta.Job)
})
_sym_db.RegisterMessage(Job)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR': _TASK,
  '__module__': 'meta_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.meta.Task)
})
_sym_db.RegisterMessage(Task)

# @@protoc_insertion_point(module_scope)
