# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import deepspeed_download_pb2 as deepspeed__download__pb2


class DsDownloadServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.download = channel.unary_unary(
                '/com.webank.eggroll.core.meta.DsDownloadService/download',
                request_serializer=deepspeed__download__pb2.DsDownloadRequest.SerializeToString,
                response_deserializer=deepspeed__download__pb2.DsDownloadResponse.FromString,
                )
        self.download_by_split = channel.unary_stream(
                '/com.webank.eggroll.core.meta.DsDownloadService/download_by_split',
                request_serializer=deepspeed__download__pb2.DsDownloadRequest.SerializeToString,
                response_deserializer=deepspeed__download__pb2.DsDownloadSplitResponse.FromString,
                )


class DsDownloadServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def download(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def download_by_split(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DsDownloadServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'download': grpc.unary_unary_rpc_method_handler(
                    servicer.download,
                    request_deserializer=deepspeed__download__pb2.DsDownloadRequest.FromString,
                    response_serializer=deepspeed__download__pb2.DsDownloadResponse.SerializeToString,
            ),
            'download_by_split': grpc.unary_stream_rpc_method_handler(
                    servicer.download_by_split,
                    request_deserializer=deepspeed__download__pb2.DsDownloadRequest.FromString,
                    response_serializer=deepspeed__download__pb2.DsDownloadSplitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.webank.eggroll.core.meta.DsDownloadService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DsDownloadService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.webank.eggroll.core.meta.DsDownloadService/download',
            deepspeed__download__pb2.DsDownloadRequest.SerializeToString,
            deepspeed__download__pb2.DsDownloadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def download_by_split(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.webank.eggroll.core.meta.DsDownloadService/download_by_split',
            deepspeed__download__pb2.DsDownloadRequest.SerializeToString,
            deepspeed__download__pb2.DsDownloadSplitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
