# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: computing-basic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basic_meta_pb2 as basic__meta__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='computing-basic.proto',
  package='com.webank.ai.eggroll.api.computing',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x63omputing-basic.proto\x12#com.webank.ai.eggroll.api.computing\x1a\x10\x62\x61sic-meta.proto\"\x9f\x01\n\x19\x43omputingEngineDescriptor\x12:\n\x08\x65ndpoint\x18\x01 \x01(\x0b\x32(.com.webank.ai.eggroll.api.core.Endpoint\x12\x46\n\x04type\x18\x02 \x01(\x0e\x32\x38.com.webank.ai.eggroll.api.computing.ComputingEngineType*\"\n\x13\x43omputingEngineType\x12\x0b\n\x07\x45GGROLL\x10\x00\x62\x06proto3')
  ,
  dependencies=[basic__meta__pb2.DESCRIPTOR,])

_COMPUTINGENGINETYPE = _descriptor.EnumDescriptor(
  name='ComputingEngineType',
  full_name='com.webank.ai.eggroll.api.computing.ComputingEngineType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EGGROLL', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=242,
  serialized_end=276,
)
_sym_db.RegisterEnumDescriptor(_COMPUTINGENGINETYPE)

ComputingEngineType = enum_type_wrapper.EnumTypeWrapper(_COMPUTINGENGINETYPE)
EGGROLL = 0



_COMPUTINGENGINEDESCRIPTOR = _descriptor.Descriptor(
  name='ComputingEngineDescriptor',
  full_name='com.webank.ai.eggroll.api.computing.ComputingEngineDescriptor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='com.webank.ai.eggroll.api.computing.ComputingEngineDescriptor.endpoint', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.webank.ai.eggroll.api.computing.ComputingEngineDescriptor.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=240,
)

_COMPUTINGENGINEDESCRIPTOR.fields_by_name['endpoint'].message_type = basic__meta__pb2._ENDPOINT
_COMPUTINGENGINEDESCRIPTOR.fields_by_name['type'].enum_type = _COMPUTINGENGINETYPE
DESCRIPTOR.message_types_by_name['ComputingEngineDescriptor'] = _COMPUTINGENGINEDESCRIPTOR
DESCRIPTOR.enum_types_by_name['ComputingEngineType'] = _COMPUTINGENGINETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputingEngineDescriptor = _reflection.GeneratedProtocolMessageType('ComputingEngineDescriptor', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTINGENGINEDESCRIPTOR,
  __module__ = 'computing_basic_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.eggroll.api.computing.ComputingEngineDescriptor)
  ))
_sym_db.RegisterMessage(ComputingEngineDescriptor)


# @@protoc_insertion_point(module_scope)
