# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node-manager.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basic_meta_pb2 as basic__meta__pb2
import computing_basic_pb2 as computing__basic__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='node-manager.proto',
  package='com.webank.ai.eggroll.api.framework.egg',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12node-manager.proto\x12\'com.webank.ai.eggroll.api.framework.egg\x1a\x10\x62\x61sic-meta.proto\x1a\x15\x63omputing-basic.proto\"\xb3\x01\n\x16\x43omputingEngineRequest\x12<\n\x07session\x18\x01 \x01(\x0b\x32+.com.webank.ai.eggroll.api.core.SessionInfo\x12[\n\x13\x63omputingEngineDesc\x18\x02 \x01(\x0b\x32>.com.webank.ai.eggroll.api.computing.ComputingEngineDescriptor2\xb1\x03\n\x0bNodeService\x12\x62\n\x0cgetProcessor\x12(.com.webank.ai.eggroll.api.core.Endpoint\x1a(.com.webank.ai.eggroll.api.core.Endpoint\x12o\n\x18getAllPossibleProcessors\x12(.com.webank.ai.eggroll.api.core.Endpoint\x1a).com.webank.ai.eggroll.api.core.Endpoints\x12\x63\n\rkillProcessor\x12(.com.webank.ai.eggroll.api.core.Endpoint\x1a(.com.webank.ai.eggroll.api.core.Endpoint\x12h\n\x11killAllProcessors\x12(.com.webank.ai.eggroll.api.core.Endpoint\x1a).com.webank.ai.eggroll.api.core.Endpoints2\x81\x03\n\x0eSessionService\x12n\n\x12getOrCreateSession\x12+.com.webank.ai.eggroll.api.core.SessionInfo\x1a+.com.webank.ai.eggroll.api.core.SessionInfo\x12g\n\x0bstopSession\x12+.com.webank.ai.eggroll.api.core.SessionInfo\x1a+.com.webank.ai.eggroll.api.core.SessionInfo\x12\x95\x01\n\x12getComputingEngine\x12?.com.webank.ai.eggroll.api.framework.egg.ComputingEngineRequest\x1a>.com.webank.ai.eggroll.api.computing.ComputingEngineDescriptorb\x06proto3')
  ,
  dependencies=[basic__meta__pb2.DESCRIPTOR,computing__basic__pb2.DESCRIPTOR,])




_COMPUTINGENGINEREQUEST = _descriptor.Descriptor(
  name='ComputingEngineRequest',
  full_name='com.webank.ai.eggroll.api.framework.egg.ComputingEngineRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='com.webank.ai.eggroll.api.framework.egg.ComputingEngineRequest.session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='computingEngineDesc', full_name='com.webank.ai.eggroll.api.framework.egg.ComputingEngineRequest.computingEngineDesc', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=284,
)

_COMPUTINGENGINEREQUEST.fields_by_name['session'].message_type = basic__meta__pb2._SESSIONINFO
_COMPUTINGENGINEREQUEST.fields_by_name['computingEngineDesc'].message_type = computing__basic__pb2._COMPUTINGENGINEDESCRIPTOR
DESCRIPTOR.message_types_by_name['ComputingEngineRequest'] = _COMPUTINGENGINEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ComputingEngineRequest = _reflection.GeneratedProtocolMessageType('ComputingEngineRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTINGENGINEREQUEST,
  __module__ = 'node_manager_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.ai.eggroll.api.framework.egg.ComputingEngineRequest)
  ))
_sym_db.RegisterMessage(ComputingEngineRequest)



_NODESERVICE = _descriptor.ServiceDescriptor(
  name='NodeService',
  full_name='com.webank.ai.eggroll.api.framework.egg.NodeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=287,
  serialized_end=720,
  methods=[
  _descriptor.MethodDescriptor(
    name='getProcessor',
    full_name='com.webank.ai.eggroll.api.framework.egg.NodeService.getProcessor',
    index=0,
    containing_service=None,
    input_type=basic__meta__pb2._ENDPOINT,
    output_type=basic__meta__pb2._ENDPOINT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getAllPossibleProcessors',
    full_name='com.webank.ai.eggroll.api.framework.egg.NodeService.getAllPossibleProcessors',
    index=1,
    containing_service=None,
    input_type=basic__meta__pb2._ENDPOINT,
    output_type=basic__meta__pb2._ENDPOINTS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='killProcessor',
    full_name='com.webank.ai.eggroll.api.framework.egg.NodeService.killProcessor',
    index=2,
    containing_service=None,
    input_type=basic__meta__pb2._ENDPOINT,
    output_type=basic__meta__pb2._ENDPOINT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='killAllProcessors',
    full_name='com.webank.ai.eggroll.api.framework.egg.NodeService.killAllProcessors',
    index=3,
    containing_service=None,
    input_type=basic__meta__pb2._ENDPOINT,
    output_type=basic__meta__pb2._ENDPOINTS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NODESERVICE)

DESCRIPTOR.services_by_name['NodeService'] = _NODESERVICE


_SESSIONSERVICE = _descriptor.ServiceDescriptor(
  name='SessionService',
  full_name='com.webank.ai.eggroll.api.framework.egg.SessionService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=723,
  serialized_end=1108,
  methods=[
  _descriptor.MethodDescriptor(
    name='getOrCreateSession',
    full_name='com.webank.ai.eggroll.api.framework.egg.SessionService.getOrCreateSession',
    index=0,
    containing_service=None,
    input_type=basic__meta__pb2._SESSIONINFO,
    output_type=basic__meta__pb2._SESSIONINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopSession',
    full_name='com.webank.ai.eggroll.api.framework.egg.SessionService.stopSession',
    index=1,
    containing_service=None,
    input_type=basic__meta__pb2._SESSIONINFO,
    output_type=basic__meta__pb2._SESSIONINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getComputingEngine',
    full_name='com.webank.ai.eggroll.api.framework.egg.SessionService.getComputingEngine',
    index=2,
    containing_service=None,
    input_type=_COMPUTINGENGINEREQUEST,
    output_type=computing__basic__pb2._COMPUTINGENGINEDESCRIPTOR,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SESSIONSERVICE)

DESCRIPTOR.services_by_name['SessionService'] = _SESSIONSERVICE

# @@protoc_insertion_point(module_scope)
