"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright 2019 The Eggroll Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Endpoint(google.protobuf.message.Message):
    """network endpoint"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IP_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    HOSTNAME_FIELD_NUMBER: builtins.int
    ip: builtins.str
    """ip address"""
    port: builtins.int
    """port"""
    hostname: builtins.str
    """host name"""
    def __init__(
        self,
        *,
        ip: builtins.str = ...,
        port: builtins.int = ...,
        hostname: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["hostname", b"hostname", "ip", b"ip", "port", b"port"]) -> None: ...

global___Endpoint = Endpoint

@typing_extensions.final
class Endpoints(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENDPOINTS_FIELD_NUMBER: builtins.int
    @property
    def endpoints(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Endpoint]: ...
    def __init__(
        self,
        *,
        endpoints: collections.abc.Iterable[global___Endpoint] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["endpoints", b"endpoints"]) -> None: ...

global___Endpoints = Endpoints

@typing_extensions.final
class Data(google.protobuf.message.Message):
    """general container for serialized data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISNULL_FIELD_NUMBER: builtins.int
    HOSTLANGUAGE_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    isNull: builtins.bool
    """whether the data is actually 'null' (e.g. null in Java, None in python, NULL in c/c++"""
    hostLanguage: builtins.str
    """the host language which serializes it"""
    type: builtins.str
    """data type in host language"""
    data: builtins.bytes
    """actual data serialized in bytes"""
    def __init__(
        self,
        *,
        isNull: builtins.bool = ...,
        hostLanguage: builtins.str = ...,
        type: builtins.str = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "hostLanguage", b"hostLanguage", "isNull", b"isNull", "type", b"type"]) -> None: ...

global___Data = Data

@typing_extensions.final
class RepeatedData(google.protobuf.message.Message):
    """general container for data list"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATALIST_FIELD_NUMBER: builtins.int
    @property
    def datalist(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Data]:
        """list of data"""
    def __init__(
        self,
        *,
        datalist: collections.abc.Iterable[global___Data] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["datalist", b"datalist"]) -> None: ...

global___RepeatedData = RepeatedData

@typing_extensions.final
class CallRequest(google.protobuf.message.Message):
    """general message for a call request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ISASYNC_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    PARAM_FIELD_NUMBER: builtins.int
    isAsync: builtins.bool
    """whether the call is async. ignored in phase 1"""
    timeout: builtins.int
    """in ms"""
    command: builtins.str
    """call command. ignored in phase 1"""
    @property
    def param(self) -> global___Data:
        """call input param"""
    def __init__(
        self,
        *,
        isAsync: builtins.bool = ...,
        timeout: builtins.int = ...,
        command: builtins.str = ...,
        param: global___Data | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["param", b"param"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["command", b"command", "isAsync", b"isAsync", "param", b"param", "timeout", b"timeout"]) -> None: ...

global___CallRequest = CallRequest

@typing_extensions.final
class CallResponse(google.protobuf.message.Message):
    """general message for a call response
    todo: merge call response with Return Status
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RETURNSTATUS_FIELD_NUMBER: builtins.int
    RESULT_FIELD_NUMBER: builtins.int
    @property
    def returnStatus(self) -> global___ReturnStatus:
        """return status"""
    @property
    def result(self) -> global___Data:
        """call result"""
    def __init__(
        self,
        *,
        returnStatus: global___ReturnStatus | None = ...,
        result: global___Data | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["result", b"result", "returnStatus", b"returnStatus"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["result", b"result", "returnStatus", b"returnStatus"]) -> None: ...

global___CallResponse = CallResponse

@typing_extensions.final
class Job(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOBID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    jobId: builtins.str
    name: builtins.str
    def __init__(
        self,
        *,
        jobId: builtins.str = ...,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["jobId", b"jobId", "name", b"name"]) -> None: ...

global___Job = Job

@typing_extensions.final
class Task(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_FIELD_NUMBER: builtins.int
    TASKID_FIELD_NUMBER: builtins.int
    TABLEID_FIELD_NUMBER: builtins.int
    @property
    def job(self) -> global___Job: ...
    taskId: builtins.int
    tableId: builtins.int
    def __init__(
        self,
        *,
        job: global___Job | None = ...,
        taskId: builtins.int = ...,
        tableId: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["job", b"job"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["job", b"job", "tableId", b"tableId", "taskId", b"taskId"]) -> None: ...

global___Task = Task

@typing_extensions.final
class Result(google.protobuf.message.Message):
    """reserved for driver async call result"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASK_FIELD_NUMBER: builtins.int
    RESULTID_FIELD_NUMBER: builtins.int
    @property
    def task(self) -> global___Task: ...
    resultId: builtins.int
    def __init__(
        self,
        *,
        task: global___Task | None = ...,
        resultId: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["task", b"task"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["resultId", b"resultId", "task", b"task"]) -> None: ...

global___Result = Result

@typing_extensions.final
class ReturnStatus(google.protobuf.message.Message):
    """generic return status"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    code: builtins.int
    message: builtins.str
    def __init__(
        self,
        *,
        code: builtins.int = ...,
        message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "message", b"message"]) -> None: ...

global___ReturnStatus = ReturnStatus

@typing_extensions.final
class SessionInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class ComputingEngineConfEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SESSIONID_FIELD_NUMBER: builtins.int
    COMPUTINGENGINECONF_FIELD_NUMBER: builtins.int
    NAMINGPOLICY_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    sessionId: builtins.str
    @property
    def computingEngineConf(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    namingPolicy: builtins.str
    tag: builtins.str
    def __init__(
        self,
        *,
        sessionId: builtins.str = ...,
        computingEngineConf: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        namingPolicy: builtins.str = ...,
        tag: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["computingEngineConf", b"computingEngineConf", "namingPolicy", b"namingPolicy", "sessionId", b"sessionId", "tag", b"tag"]) -> None: ...

global___SessionInfo = SessionInfo
