"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import containers_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class PrepareDownloadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    RANKS_FIELD_NUMBER: builtins.int
    COMPRESS_METHOD_FIELD_NUMBER: builtins.int
    COMPRESS_LEVEL_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    @property
    def ranks(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    compress_method: builtins.str
    compress_level: builtins.int
    content_type: containers_pb2.ContentType.ValueType
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        ranks: collections.abc.Iterable[builtins.int] | None = ...,
        compress_method: builtins.str = ...,
        compress_level: builtins.int = ...,
        content_type: containers_pb2.ContentType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["compress_level", b"compress_level", "compress_method", b"compress_method", "content_type", b"content_type", "ranks", b"ranks", "session_id", b"session_id"]) -> None: ...

global___PrepareDownloadRequest = PrepareDownloadRequest

@typing_extensions.final
class PrepareDownloadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    content: builtins.str
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        content: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["content", b"content", "session_id", b"session_id"]) -> None: ...

global___PrepareDownloadResponse = PrepareDownloadResponse

@typing_extensions.final
class DsDownloadRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    RANKS_FIELD_NUMBER: builtins.int
    COMPRESS_METHOD_FIELD_NUMBER: builtins.int
    COMPRESS_LEVEL_FIELD_NUMBER: builtins.int
    CONTENT_TYPE_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    @property
    def ranks(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    compress_method: builtins.str
    compress_level: builtins.int
    content_type: containers_pb2.ContentType.ValueType
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        ranks: collections.abc.Iterable[builtins.int] | None = ...,
        compress_method: builtins.str = ...,
        compress_level: builtins.int = ...,
        content_type: containers_pb2.ContentType.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["compress_level", b"compress_level", "compress_method", b"compress_method", "content_type", b"content_type", "ranks", b"ranks", "session_id", b"session_id"]) -> None: ...

global___DsDownloadRequest = DsDownloadRequest

@typing_extensions.final
class DsDownloadResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    CONTAINER_CONTENT_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    @property
    def container_content(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[containers_pb2.ContainerContent]: ...
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        container_content: collections.abc.Iterable[containers_pb2.ContainerContent] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["container_content", b"container_content", "session_id", b"session_id"]) -> None: ...

global___DsDownloadResponse = DsDownloadResponse

@typing_extensions.final
class DsDownloadSplitResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    RANK_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    rank: builtins.int
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        rank: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "rank", b"rank"]) -> None: ...

global___DsDownloadSplitResponse = DsDownloadSplitResponse
