"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright (c) 2019 - now, Eggroll Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GetLogRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSIONID_FIELD_NUMBER: builtins.int
    RANK_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    STARTLINE_FIELD_NUMBER: builtins.int
    LOGTYPE_FIELD_NUMBER: builtins.int
    sessionId: builtins.str
    rank: builtins.str
    path: builtins.str
    startLine: builtins.int
    logType: builtins.str
    def __init__(
        self,
        *,
        sessionId: builtins.str = ...,
        rank: builtins.str = ...,
        path: builtins.str = ...,
        startLine: builtins.int = ...,
        logType: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["logType", b"logType", "path", b"path", "rank", b"rank", "sessionId", b"sessionId", "startLine", b"startLine"]) -> None: ...

global___GetLogRequest = GetLogRequest

@typing_extensions.final
class GetLogResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    DATAS_FIELD_NUMBER: builtins.int
    MSG_FIELD_NUMBER: builtins.int
    code: builtins.str
    @property
    def datas(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    msg: builtins.str
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        datas: collections.abc.Iterable[builtins.str] | None = ...,
        msg: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["code", b"code", "datas", b"datas", "msg", b"msg"]) -> None: ...

global___GetLogResponse = GetLogResponse
