# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import store_pb2 as store__pb2


class RendezvousStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Set = channel.unary_unary(
                '/com.webank.eggroll.core.meta.RendezvousStore/Set',
                request_serializer=store__pb2.SetRequest.SerializeToString,
                response_deserializer=store__pb2.SetResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/com.webank.eggroll.core.meta.RendezvousStore/Get',
                request_serializer=store__pb2.GetRequest.SerializeToString,
                response_deserializer=store__pb2.GetResponse.FromString,
                )
        self.Add = channel.unary_unary(
                '/com.webank.eggroll.core.meta.RendezvousStore/Add',
                request_serializer=store__pb2.AddRequest.SerializeToString,
                response_deserializer=store__pb2.AddResponse.FromString,
                )
        self.CompareAndSet = channel.unary_unary(
                '/com.webank.eggroll.core.meta.RendezvousStore/CompareAndSet',
                request_serializer=store__pb2.CompareAndSetRequest.SerializeToString,
                response_deserializer=store__pb2.CompareAndSetResponse.FromString,
                )
        self.Wait = channel.unary_unary(
                '/com.webank.eggroll.core.meta.RendezvousStore/Wait',
                request_serializer=store__pb2.WaitRequest.SerializeToString,
                response_deserializer=store__pb2.WaitResponse.FromString,
                )
        self.NumKeys = channel.unary_unary(
                '/com.webank.eggroll.core.meta.RendezvousStore/NumKeys',
                request_serializer=store__pb2.NumKeysRequest.SerializeToString,
                response_deserializer=store__pb2.NumKeysResponse.FromString,
                )
        self.DeleteKey = channel.unary_unary(
                '/com.webank.eggroll.core.meta.RendezvousStore/DeleteKey',
                request_serializer=store__pb2.DeleteKeyRequest.SerializeToString,
                response_deserializer=store__pb2.DeleteKeyResponse.FromString,
                )


class RendezvousStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompareAndSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Wait(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NumKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RendezvousStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Set': grpc.unary_unary_rpc_method_handler(
                    servicer.Set,
                    request_deserializer=store__pb2.SetRequest.FromString,
                    response_serializer=store__pb2.SetResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=store__pb2.GetRequest.FromString,
                    response_serializer=store__pb2.GetResponse.SerializeToString,
            ),
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=store__pb2.AddRequest.FromString,
                    response_serializer=store__pb2.AddResponse.SerializeToString,
            ),
            'CompareAndSet': grpc.unary_unary_rpc_method_handler(
                    servicer.CompareAndSet,
                    request_deserializer=store__pb2.CompareAndSetRequest.FromString,
                    response_serializer=store__pb2.CompareAndSetResponse.SerializeToString,
            ),
            'Wait': grpc.unary_unary_rpc_method_handler(
                    servicer.Wait,
                    request_deserializer=store__pb2.WaitRequest.FromString,
                    response_serializer=store__pb2.WaitResponse.SerializeToString,
            ),
            'NumKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.NumKeys,
                    request_deserializer=store__pb2.NumKeysRequest.FromString,
                    response_serializer=store__pb2.NumKeysResponse.SerializeToString,
            ),
            'DeleteKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKey,
                    request_deserializer=store__pb2.DeleteKeyRequest.FromString,
                    response_serializer=store__pb2.DeleteKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.webank.eggroll.core.meta.RendezvousStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RendezvousStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.webank.eggroll.core.meta.RendezvousStore/Set',
            store__pb2.SetRequest.SerializeToString,
            store__pb2.SetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.webank.eggroll.core.meta.RendezvousStore/Get',
            store__pb2.GetRequest.SerializeToString,
            store__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.webank.eggroll.core.meta.RendezvousStore/Add',
            store__pb2.AddRequest.SerializeToString,
            store__pb2.AddResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CompareAndSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.webank.eggroll.core.meta.RendezvousStore/CompareAndSet',
            store__pb2.CompareAndSetRequest.SerializeToString,
            store__pb2.CompareAndSetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Wait(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.webank.eggroll.core.meta.RendezvousStore/Wait',
            store__pb2.WaitRequest.SerializeToString,
            store__pb2.WaitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NumKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.webank.eggroll.core.meta.RendezvousStore/NumKeys',
            store__pb2.NumKeysRequest.SerializeToString,
            store__pb2.NumKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.webank.eggroll.core.meta.RendezvousStore/DeleteKey',
            store__pb2.DeleteKeyRequest.SerializeToString,
            store__pb2.DeleteKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
