"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file

Copyright (c) 2019 - now, Eggroll Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TransferHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    TOTALSIZE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    EXT_FIELD_NUMBER: builtins.int
    id: builtins.int
    tag: builtins.str
    totalSize: builtins.int
    status: builtins.str
    ext: builtins.bytes
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        tag: builtins.str = ...,
        totalSize: builtins.int = ...,
        status: builtins.str = ...,
        ext: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ext", b"ext", "id", b"id", "status", b"status", "tag", b"tag", "totalSize", b"totalSize"]) -> None: ...

global___TransferHeader = TransferHeader

@typing_extensions.final
class TransferBatch(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    BATCHSIZE_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___TransferHeader: ...
    batchSize: builtins.int
    data: builtins.bytes
    def __init__(
        self,
        *,
        header: global___TransferHeader | None = ...,
        batchSize: builtins.int = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["batchSize", b"batchSize", "data", b"data", "header", b"header"]) -> None: ...

global___TransferBatch = TransferBatch

@typing_extensions.final
class RollSiteHeader(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class OptionsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    ROLLSITESESSIONID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    SRCROLE_FIELD_NUMBER: builtins.int
    SRCPARTYID_FIELD_NUMBER: builtins.int
    DSTROLE_FIELD_NUMBER: builtins.int
    DSTPARTYID_FIELD_NUMBER: builtins.int
    DATATYPE_FIELD_NUMBER: builtins.int
    OPTIONS_FIELD_NUMBER: builtins.int
    TOTALPARTITIONS_FIELD_NUMBER: builtins.int
    PARTITIONID_FIELD_NUMBER: builtins.int
    TOTALSTREAMS_FIELD_NUMBER: builtins.int
    TOTALBATCHES_FIELD_NUMBER: builtins.int
    STREAMSEQ_FIELD_NUMBER: builtins.int
    BATCHSEQ_FIELD_NUMBER: builtins.int
    STAGE_FIELD_NUMBER: builtins.int
    rollSiteSessionId: builtins.str
    name: builtins.str
    tag: builtins.str
    srcRole: builtins.str
    srcPartyId: builtins.str
    dstRole: builtins.str
    dstPartyId: builtins.str
    dataType: builtins.str
    @property
    def options(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    totalPartitions: builtins.int
    partitionId: builtins.int
    totalStreams: builtins.int
    totalBatches: builtins.int
    streamSeq: builtins.int
    batchSeq: builtins.int
    stage: builtins.str
    def __init__(
        self,
        *,
        rollSiteSessionId: builtins.str = ...,
        name: builtins.str = ...,
        tag: builtins.str = ...,
        srcRole: builtins.str = ...,
        srcPartyId: builtins.str = ...,
        dstRole: builtins.str = ...,
        dstPartyId: builtins.str = ...,
        dataType: builtins.str = ...,
        options: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        totalPartitions: builtins.int = ...,
        partitionId: builtins.int = ...,
        totalStreams: builtins.int = ...,
        totalBatches: builtins.int = ...,
        streamSeq: builtins.int = ...,
        batchSeq: builtins.int = ...,
        stage: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["batchSeq", b"batchSeq", "dataType", b"dataType", "dstPartyId", b"dstPartyId", "dstRole", b"dstRole", "name", b"name", "options", b"options", "partitionId", b"partitionId", "rollSiteSessionId", b"rollSiteSessionId", "srcPartyId", b"srcPartyId", "srcRole", b"srcRole", "stage", b"stage", "streamSeq", b"streamSeq", "tag", b"tag", "totalBatches", b"totalBatches", "totalPartitions", b"totalPartitions", "totalStreams", b"totalStreams"]) -> None: ...

global___RollSiteHeader = RollSiteHeader

@typing_extensions.final
class RollSitePullGetHeaderRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    tag: builtins.str
    timeout: builtins.float
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        timeout: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tag", b"tag", "timeout", b"timeout"]) -> None: ...

global___RollSitePullGetHeaderRequest = RollSitePullGetHeaderRequest

@typing_extensions.final
class RollSitePullGetHeaderResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEADER_FIELD_NUMBER: builtins.int
    @property
    def header(self) -> global___RollSiteHeader: ...
    def __init__(
        self,
        *,
        header: global___RollSiteHeader | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["header", b"header"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["header", b"header"]) -> None: ...

global___RollSitePullGetHeaderResponse = RollSitePullGetHeaderResponse

@typing_extensions.final
class RollSitePullGetPartitionStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    TIMEOUT_FIELD_NUMBER: builtins.int
    tag: builtins.str
    timeout: builtins.float
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
        timeout: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tag", b"tag", "timeout", b"timeout"]) -> None: ...

global___RollSitePullGetPartitionStatusRequest = RollSitePullGetPartitionStatusRequest

@typing_extensions.final
class RollSitePullGetPartitionStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class IntKeyIntValuePair(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        value: builtins.int
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing_extensions.final
    class RollSitePullGetPartitionStatusResponseStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TAG_FIELD_NUMBER: builtins.int
        IS_FINISHED_FIELD_NUMBER: builtins.int
        TOTAL_BATCHES_FIELD_NUMBER: builtins.int
        BATCH_SEQ_TO_PAIR_COUNTER_FIELD_NUMBER: builtins.int
        TOTAL_STREAMS_FIELD_NUMBER: builtins.int
        STREAM_SEQ_TO_PAIR_COUNTER_FIELD_NUMBER: builtins.int
        STREAM_SEQ_TO_BATCH_SEQ_FIELD_NUMBER: builtins.int
        TOTAL_PAIRS_FIELD_NUMBER: builtins.int
        DATA_TYPE_FIELD_NUMBER: builtins.int
        tag: builtins.str
        is_finished: builtins.bool
        total_batches: builtins.int
        @property
        def batch_seq_to_pair_counter(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RollSitePullGetPartitionStatusResponse.IntKeyIntValuePair]: ...
        total_streams: builtins.int
        @property
        def stream_seq_to_pair_counter(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RollSitePullGetPartitionStatusResponse.IntKeyIntValuePair]: ...
        @property
        def stream_seq_to_batch_seq(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RollSitePullGetPartitionStatusResponse.IntKeyIntValuePair]: ...
        total_pairs: builtins.int
        data_type: builtins.str
        def __init__(
            self,
            *,
            tag: builtins.str = ...,
            is_finished: builtins.bool = ...,
            total_batches: builtins.int = ...,
            batch_seq_to_pair_counter: collections.abc.Iterable[global___RollSitePullGetPartitionStatusResponse.IntKeyIntValuePair] | None = ...,
            total_streams: builtins.int = ...,
            stream_seq_to_pair_counter: collections.abc.Iterable[global___RollSitePullGetPartitionStatusResponse.IntKeyIntValuePair] | None = ...,
            stream_seq_to_batch_seq: collections.abc.Iterable[global___RollSitePullGetPartitionStatusResponse.IntKeyIntValuePair] | None = ...,
            total_pairs: builtins.int = ...,
            data_type: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["batch_seq_to_pair_counter", b"batch_seq_to_pair_counter", "data_type", b"data_type", "is_finished", b"is_finished", "stream_seq_to_batch_seq", b"stream_seq_to_batch_seq", "stream_seq_to_pair_counter", b"stream_seq_to_pair_counter", "tag", b"tag", "total_batches", b"total_batches", "total_pairs", b"total_pairs", "total_streams", b"total_streams"]) -> None: ...

    PARTITION_ID_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    partition_id: builtins.int
    @property
    def status(self) -> global___RollSitePullGetPartitionStatusResponse.RollSitePullGetPartitionStatusResponseStatus: ...
    def __init__(
        self,
        *,
        partition_id: builtins.int = ...,
        status: global___RollSitePullGetPartitionStatusResponse.RollSitePullGetPartitionStatusResponseStatus | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["status", b"status"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["partition_id", b"partition_id", "status", b"status"]) -> None: ...

global___RollSitePullGetPartitionStatusResponse = RollSitePullGetPartitionStatusResponse

@typing_extensions.final
class RollSitePullClearStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    tag: builtins.str
    def __init__(
        self,
        *,
        tag: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["tag", b"tag"]) -> None: ...

global___RollSitePullClearStatusRequest = RollSitePullClearStatusRequest

@typing_extensions.final
class RollSitePullClearStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___RollSitePullClearStatusResponse = RollSitePullClearStatusResponse
