# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: extend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='extend.proto',
  package='com.webank.eggroll.core.transfer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x65xtend.proto\x12 com.webank.eggroll.core.transfer\"b\n\rGetLogRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12\x11\n\tstartLine\x18\x04 \x01(\x05\x12\x0f\n\x07logType\x18\x05 \x01(\t\":\n\x0eGetLogResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\r\n\x05\x64\x61tas\x18\x02 \x03(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t2\x87\x01\n\x14\x45xtendTransferServer\x12o\n\x06getLog\x12/.com.webank.eggroll.core.transfer.GetLogRequest\x1a\x30.com.webank.eggroll.core.transfer.GetLogResponse(\x01\x30\x01\x62\x06proto3')
)




_GETLOGREQUEST = _descriptor.Descriptor(
  name='GetLogRequest',
  full_name='com.webank.eggroll.core.transfer.GetLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionId', full_name='com.webank.eggroll.core.transfer.GetLogRequest.sessionId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rank', full_name='com.webank.eggroll.core.transfer.GetLogRequest.rank', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='com.webank.eggroll.core.transfer.GetLogRequest.path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startLine', full_name='com.webank.eggroll.core.transfer.GetLogRequest.startLine', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logType', full_name='com.webank.eggroll.core.transfer.GetLogRequest.logType', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=148,
)


_GETLOGRESPONSE = _descriptor.Descriptor(
  name='GetLogResponse',
  full_name='com.webank.eggroll.core.transfer.GetLogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='com.webank.eggroll.core.transfer.GetLogResponse.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='datas', full_name='com.webank.eggroll.core.transfer.GetLogResponse.datas', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='com.webank.eggroll.core.transfer.GetLogResponse.msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=208,
)

DESCRIPTOR.message_types_by_name['GetLogRequest'] = _GETLOGREQUEST
DESCRIPTOR.message_types_by_name['GetLogResponse'] = _GETLOGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetLogRequest = _reflection.GeneratedProtocolMessageType('GetLogRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETLOGREQUEST,
  '__module__' : 'extend_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.transfer.GetLogRequest)
  })
_sym_db.RegisterMessage(GetLogRequest)

GetLogResponse = _reflection.GeneratedProtocolMessageType('GetLogResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETLOGRESPONSE,
  '__module__' : 'extend_pb2'
  # @@protoc_insertion_point(class_scope:com.webank.eggroll.core.transfer.GetLogResponse)
  })
_sym_db.RegisterMessage(GetLogResponse)



_EXTENDTRANSFERSERVER = _descriptor.ServiceDescriptor(
  name='ExtendTransferServer',
  full_name='com.webank.eggroll.core.transfer.ExtendTransferServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=211,
  serialized_end=346,
  methods=[
  _descriptor.MethodDescriptor(
    name='getLog',
    full_name='com.webank.eggroll.core.transfer.ExtendTransferServer.getLog',
    index=0,
    containing_service=None,
    input_type=_GETLOGREQUEST,
    output_type=_GETLOGRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXTENDTRANSFERSERVER)

DESCRIPTOR.services_by_name['ExtendTransferServer'] = _EXTENDTRANSFERSERVER

# @@protoc_insertion_point(module_scope)
